name: 构建JD Scripts镜像

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "jd_scripts/Dockerfile"
  repository_dispatch:
    types: jd_scripts

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - id: repo_name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository_owner }}

      - name: "add secrets to file"
        run: |
          echo $JDS_SSHKEY > ./jd_scripts/id_rsa
          sed -i "s/KEY----- /&\\n/g;s/-----END/\\n&/g" ./jd_scripts/id_rsa
          sed -i "/\(KEY\)/!s/ /\\n/g" ./jd_scripts/id_rsa
          sed -i /^[[:space:]]*$/d  ./jd_scripts/id_rsa
        env:
          JDS_SSHKEY: ${{ secrets.$JDS_SSHKEY }}

      - name: 构建并推送到Dockerhub和ghcr.io镜像仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./jd_scripts/Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            akyakya/jd_scripts:latest
            ghcr.io/${{ steps.repo_name.outputs.lowercase }}/jd_scripts:latest

      - name: 构建基于alpine3.12的镜像并推送到Dockerhub和ghcr.io镜像仓库
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./jd_scripts/Dockerfile.alpine312
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            akyakya/jd_scripts:alpine3.12
            ghcr.io/${{ steps.repo_name.outputs.lowercase }}/jd_scripts:alpine3.12
